# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=60)),
                ('gradonombre', models.CharField(max_length=60)),
                ('gradoseccion', models.CharField(max_length=60)),
                ('anio', models.IntegerField()),
                ('materias', models.ManyToManyField(through='notas.Asignacion', to='notas.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='Materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Materia'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='Pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Pensum'),
        ),
    ]
